export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/admin/auth/login',
    LOGOUT: '/admin/auth/logout',
    ME: '/admin/auth/me',
  },
  METRICS: {
    OVERVIEW: '/admin/metrics/overview',
    REVENUE: '/admin/metrics/revenue',
    USER_ACQUISITION: '/admin/metrics/users/acquisition',
    CONTENT_DISTRIBUTION: '/admin/metrics/content/distribution',
    ENGAGEMENT: '/admin/metrics/engagement',
    TOP_ARTISTS: '/admin/metrics/artists/top',
    TOP_CAMPAIGNS: '/admin/metrics/campaigns/top',
    DROP_PACKAGE_SALES: '/admin/metrics/drop-packages/sales',
    TRANSACTIONS: '/admin/metrics/transactions',
    PAYMENT_CHANNELS: '/admin/metrics/payment-channels',
    RECENT_ACTIVITY: '/admin/metrics/activity',
  },
  ARTISTS: {
    LIST: '/admin/artists',
    DETAIL: (id: string) => `/admin/artists/${id}`,
    VERIFY: (id: string) => `/admin/artists/${id}/verify`,
    SUSPEND: (id: string) => `/admin/artists/${id}/suspend`,
    UNSUSPEND: (id: string) => `/admin/artists/${id}/unsuspend`,
    DELETE: (id: string) => `/admin/artists/${id}`,
    CONTENT: (id: string) => `/admin/artists/${id}/content`,
    TRANSACTIONS: (id: string) => `/admin/artists/${id}/transactions`,
  },
  FANS: {
    LIST: '/admin/fans',
    DETAIL: (id: string) => `/admin/fans/${id}`,
    SUSPEND: (id: string) => `/admin/fans/${id}/suspend`,
    UNSUSPEND: (id: string) => `/admin/fans/${id}/unsuspend`,
    DELETE: (id: string) => `/admin/fans/${id}`,
    TRANSACTIONS: (id: string) => `/admin/fans/${id}/transactions`,
    FOLLOWED_ARTISTS: (id: string) => `/admin/fans/${id}/followed-artists`,
  },
  STAFF: {
    LIST: '/admin/staff',
    CREATE: '/admin/staff',
    UPDATE: (id: string) => `/admin/staff/${id}`,
    DELETE: (id: string) => `/admin/staff/${id}`,
  },
  NOTIFICATIONS: {
    SEND: '/admin/notifications/send',
    HISTORY: '/admin/notifications/history',
  },
  SETTINGS: {
    GET: '/admin/settings',
    UPDATE: '/admin/settings',
    DROP_PACKAGES: '/admin/settings/drop-packages',
    FEATURE_FLAGS: '/admin/settings/feature-flags',
  },
} as const;
